//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_esosEntities : DbContext
    {
        public db_esosEntities()
            : base("name=db_esosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<detail_roles> detail_roles { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<t_album> t_album { get; set; }
        public DbSet<t_bidang> t_bidang { get; set; }
        public DbSet<t_content> t_content { get; set; }
        public DbSet<t_csr> t_csr { get; set; }
        public DbSet<t_csr_activity> t_csr_activity { get; set; }
        public DbSet<t_csr_ph> t_csr_ph { get; set; }
        public DbSet<t_dokumentasi> t_dokumentasi { get; set; }
        public DbSet<t_donatur> t_donatur { get; set; }
        public DbSet<t_download> t_download { get; set; }
        public DbSet<t_file> t_file { get; set; }
        public DbSet<t_filemeta> t_filemeta { get; set; }
        public DbSet<t_kegiatan> t_kegiatan { get; set; }
        public DbSet<t_kesejahteraan> t_kesejahteraan { get; set; }
        public DbSet<t_news> t_news { get; set; }
        public DbSet<t_news_category> t_news_category { get; set; }
        public DbSet<t_organisasi> t_organisasi { get; set; }
        public DbSet<t_panti> t_panti { get; set; }
        public DbSet<t_program> t_program { get; set; }
        public DbSet<t_report> t_report { get; set; }
        public DbSet<t_satuan> t_satuan { get; set; }
        public DbSet<t_seksi> t_seksi { get; set; }
        public DbSet<t_visitor> t_visitor { get; set; }
        public DbSet<t_volunteer> t_volunteer { get; set; }
        public DbSet<t_wilayah> t_wilayah { get; set; }
        public DbSet<user> users { get; set; }
    }
}
