//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_roles
    {
        public int id_detail_roles { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_roles { get; set; }
    }
}
