//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class t_album
    {
        [Key]
        public int album_id { get; set; }
        public int user_id { get; set; }
        [Required(ErrorMessage="Judul album harus diisi")]
        public string album_title { get; set; }
        [AllowHtml]
        public string album_desc { get; set; }
        public System.DateTime album_date { get; set; }
    }
}
