//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_bidang
    {
        public int bidang_id { get; set; }
        public int user_id { get; set; }
        public string bidang_title { get; set; }
        public string bidang_name { get; set; }
        public string bidang_person_foto { get; set; }
        public string bidang_desc { get; set; }
        public System.DateTime bidang_date { get; set; }
        public string bidang_desc_foto { get; set; }
    }
}
