//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class t_content
    {
        [Key]
        public long content_id { get; set; }
        [Required(ErrorMessage="Nama prosedur harus diisi")]
        [StringLength(100)]
        public string content_name { get; set; }
        public string content_type { get; set; }
        [Required(ErrorMessage = "Konten harus diisi")]
        [AllowHtml]
        public string content { get; set; }
        public long user_id { get; set; }
        public string url { get; set; }
        public System.DateTime content_time { get; set; }
    }
}
