//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class t_csr_ph
    {
        [Key]
        public int csr_ph_id { get; set; }
        [Required(ErrorMessage="Nama perusahaan harus diisi")]
        public string csr_ph_name { get; set; }
        [Required(ErrorMessage = "Alamat perusahaan harus diisi")]
        public string csr_ph_address { get; set; }
        [Required(ErrorMessage = "Aktifitas perusahaan harus diisi")]
        public string csr_ph_activity { get; set; }
        public System.DateTime csr_ph_date { get; set; }
    }
}
