//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_csr
    {
        public long csr_id { get; set; }
        public string csr_name { get; set; }
        public string csr_address { get; set; }
        public decimal csr_value { get; set; }
    }
}
