//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class t_donatur
    {
        [Key]
        public long donatur_id { get; set; }
        [Required(ErrorMessage="Nama donatur harus diisi.")]
        public string donatur_name { get; set; }
        [Required(ErrorMessage = "Telepon donatur harus diisi.")]
        public string donatur_phone { get; set; }
        [Required(ErrorMessage = "Alamat donatur harus diisi.")]
        public string donatur_address { get; set; }
        [EmailAddress(ErrorMessage="Format email harus benar.")]
        public string donatur_email { get; set; }
        [Required(ErrorMessage="Jumlah donasi harus diisi.")]
        public long donasi { get; set; }
        [Required(ErrorMessage = "Pembayaran harus diisi")]
        public string pembayaran { get; set; }
        public int report_id { get; set; }
    }
}
