//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_dokumentasi
    {
        public int dokumentasi_id { get; set; }
        public int album_id { get; set; }
        public string dokumentasi_path { get; set; }
        public string dokumentasi_title { get; set; }
        public string dokumentasi_type { get; set; }
        public System.DateTime dokumentasi_date { get; set; }
    }
}
