//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class t_download
    {
        [Key]
        public int download_id { get; set; }
        [Required(ErrorMessage="Judul harus diisi")]
        public string download_title { get; set; }
        public string download_path { get; set; }
        public string download_desc { get; set; }
        public System.DateTime download_date { get; set; }
        public int user_id { get; set; }
    }
}
