//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class t_file
    {
        [Key]
        public long file_id { get; set; }
        public string file_title { get; set; }
        public string file_name { get; set; }
        [StringLength(200)]
        public string file_location { get; set; }
        [StringLength(200)]
        public string file_url { get; set; }
        public long user_id { get; set; }
        public string mime_type { get; set; }
        public string file_category { get; set; }
        public int file_parent { get; set; }
    }
}
