//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_filemeta
    {
        public long fmeta_id { get; set; }
        public long file_id { get; set; }
        public string fmeta_key { get; set; }
        public string fmeta_value { get; set; }
    }
}
