//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class t_kegiatan
    {
        [Key]
        public int kegiatan_id { get; set; }
        public int user_id { get; set; }
        public int wilayah_id { get; set; }
        [Required(ErrorMessage="Nama kegiatan harus diisi")]
        public string kegiatan_nama { get; set; }
        [Required(ErrorMessage="Deskripsi kegiatan harus diisi")]
        [AllowHtml]
        public string kegiatan_deskripsi { get; set; }
        public System.DateTime kegiatan_tgl_update { get; set; }
        [Required(ErrorMessage="Tanggal pelaksanaan acara harus diisi")]
        public System.DateTime kegiatan_tgl_acara { get; set; }
    }
}
