//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class t_kesejahteraan
    {
        [Key]
        public int ks_id { get; set; }
        [Required(ErrorMessage = "Nama Harus diisi")]
        public string ks_name { get; set; }
        [Required(ErrorMessage = "Jumlah harus diisi")]
        public int ks_jumlah { get; set; }
        public string ks_type { get; set; }
        [Required(ErrorMessage = "Satuan harus diisi")]
        public int ks_satuan { get; set; }
        public System.DateTime ks_date { get; set; }
        [Required(ErrorMessage="Tahun harus diisi")]
        [Range(1900,2200,ErrorMessage="Tahun harus sesuai (Cth : 2014)")]
        public Nullable<short> ks_year { get; set; }
    }
}
