//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class t_news
    {
        [Key]
        public int news_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime news_date { get; set; }
        [Required(ErrorMessage="Judul harus diisi")]
        public string news_title { get; set; }
        [Required(ErrorMessage="Konten harus diisi")]
        [AllowHtml]
        public string news_content { get; set; }
        [Required(ErrorMessage = "Status harus diisi")]
        public string news_status { get; set; }
        public System.DateTime news_modified { get; set; }
        public int news_parent { get; set; }
        [Required(ErrorMessage = "Tipe harus diisi")]
        public string news_type { get; set; }
        [Required(ErrorMessage = "Sumber berita harus diisi")]
        [AllowHtml]
        public string news_url { get; set; }
        [Required(ErrorMessage = "Kategori harus diisi")]
        public int news_category { get; set; }
    }
}
