//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class t_news_category
    {
        [Key]
        public long news_category_id { get; set; }
        public long user_id { get; set; }
        [Required(ErrorMessage="Nama kategori harus diisi")]
        public string category_title { get; set; }
        public System.DateTime category_date { get; set; }
    }
}
