//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_organisasi
    {
        public int t_organisasi1 { get; set; }
        public string t_nama { get; set; }
        public string t_jabatan { get; set; }
        public string t_path { get; set; }
    }
}
