//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_panti
    {
        public long panti_id { get; set; }
        public string panti_name { get; set; }
        public long wil_id { get; set; }
        public string panti_lead { get; set; }
        public int penghuni { get; set; }
        public string panti_phone { get; set; }
        public string panti_address { get; set; }
    }
}
