//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_program
    {
        public long prog_id { get; set; }
        public string prog_name { get; set; }
        public string prog_description { get; set; }
        public int csr_id { get; set; }
        public string prog_place { get; set; }
        public System.DateTime prog_time { get; set; }
        public string prog_type { get; set; }
    }
}
