//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class t_report
    {
        [Key]
        public long report_id { get; set; }
        [Required(ErrorMessage="Pelapor harus diisi")]
        public string report_author { get; set; }
        public long wil_id { get; set; }
        [Required(ErrorMessage="Alamat pelapor harus diisi")]
        public string address { get; set; }
        [Required(ErrorMessage="Telepon pelapor harus diisi")]
        public string phone { get; set; }
        [Required(ErrorMessage="Konten bencana harus diisi")]
        [AllowHtml]
        public string report_content { get; set; }
        public System.DateTime report_time { get; set; }
    }
}
