//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class t_satuan
    {
        [Key]
        public int id_satuan { get; set; }
        [Required(ErrorMessage="Nama satuan harus diisi")]
        public string satuan { get; set; }
        public System.DateTime tanggal { get; set; }
    }
}
