//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class t_seksi
    {
        public int seksi_id { get; set; }
        public int user_id { get; set; }
        [StringLength(99)]
        public string seksi_title { get; set; }
        public string seksi_name { get; set; }
        public string seksi_foto { get; set; }
        public string seksi_description { get; set; }
        public System.DateTime seksi_date { get; set; }
        public string seksi_desc_foto { get; set; }
        public int bidang_id { get; set; }
    }
}
