//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_visitor
    {
        public int visitor_id { get; set; }
        public System.DateTime date { get; set; }
        public int hits { get; set; }
        public string online { get; set; }
        public string visitor_ip { get; set; }
    }
}
