//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class t_volunteer
    {
        [Key]
        public long vol_id { get; set; }
        [Required(ErrorMessage="No. KTP harus diisi")]
        [RegularExpression("^[0-9]{18}$", ErrorMessage = "No. KTP harus berupa 18 angka")]
        public string vol_card_id { get; set; }
        [Required(ErrorMessage="Nama harus diisi")]
        public string vol_name { get; set; }
        [Required(ErrorMessage="Handphone harus diisi")]
        [RegularExpression("^[0-9]{6,12}$", ErrorMessage = "No. handphone salah harus berupa 6-12 angka")]
        public string vol_phone { get; set; }
        [Required(ErrorMessage="Alamat harus diisi")]
        public string vol_address { get; set; }
        [Required(ErrorMessage="Pekerjaan harus diisi")]
        public string vol_occupation { get; set; }
        [Required(ErrorMessage="E-Mail harus diisi")]
        [EmailAddress(ErrorMessage="Penulisan email contoh@contoh.com")]
        public string vol_email { get; set; }
        public int kegiatan_id { get; set; }
    }
}
