//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id_user { get; set; }
        public string username { get; set; }
        public string user_password { get; set; }
        public string user_passwordsalt { get; set; }
        public string nama { get; set; }
        public string email { get; set; }
        public string hp { get; set; }
        public string alamat { get; set; }
        public System.DateTime tanggal { get; set; }
    }
}
